<?php
define('HOST_DB','localhost');
define('NAME_DB','ly');
define('USER_DB','root');
define('PASS_DB','');
define('ROOT_URL','/ly');
define('ADMIN_URL',ROOT_URL.'/admin');
define('SITE_URL',ROOT_URL.'/site/');
define('SYSTEM_PATH',ROOT_URL.'/system');
define('PAGE_SIZE_SANPHAM',6);
define('PAGE_SIZE_BAIVIET',3);
date_default_timezone_set("Asia/Bangkok");
?>